import argparse
def args_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument('--exp', type = int, default=6, help ='exp number(default:1)')
    parser.add_argument('--iters', type = int, default=100, help = 'iterations for communication(default:300)')
    parser.add_argument('--wk_iters', type = int, default=1, help = 'optimization iters in local worker between communication(default:1")')
    parser.add_argument('--batch', type = int, default= 32, help ='batch size(default:16)')
    parser.add_argument('--lr', type=float, default=1e-3, help='learning rate')
    parser.add_argument('--number_workers', type = int, default=4, help = 'dataloader number workers(default:0)')
    parser.add_argument('--size', type = int, default= 64, help ='images input size(default:256)')
    parser.add_argument('--mode', type = str, default='ours', help='fedavg | fedprox | fedBN | SingleSet | fedproto')
    parser.add_argument('--dataset', type = str, default='digit', help='digit | domainnet | office | PACS')
    parser.add_argument('--optimizer', type = str, default='sgd', help='sgd | adam')
    parser.add_argument('--num_users', type=int, default=5, help ='the number of clients(default:5)')
    parser.add_argument('--features', type=int, default=1, help ='0 denotes non-iid features, 1 denotes iid features')
    parser.add_argument('--labels', type=int, default=0, help ='0 denotes non-iid labels, 1 denotes iid labels')
    parser.add_argument('--num_classes', type=int, default=10, help ='class numbers')
    parser.add_argument('--save_path', type = str, default=None, help='path to save the outcome')
    parser.add_argument('--device', default="cuda:0", type=str, help="cpu, cuda, or others")
    parser.add_argument('--momentum', type = float, default=1, help ='upper momentum of our algorithm')
    parser.add_argument('--loss_component', type=int, default=1, help ='loss combination')
    parser.add_argument('--cls_component', type=int, default=1, help ='classification change strategy')
    parser.add_argument('--mix_mode', type=int, default=1, help ='noise type')
    parser.add_argument('--percent', type = float, default= 0.1, help ='percentage of dataset to train for digits')
    parser.add_argument('--adcol_epoch', type = int, default=3, help = 'optimization iters in discriminator(default:3")')
    parser.add_argument('--uniform_left', type=float, default=0.8)
    parser.add_argument('--uniform_right', type=float, default=0.2)
    parser.add_argument('--adcol_mu', type=float, default=0.1, help='The hyper parameter for fedprox')
    parser.add_argument('--adcol_beta', type=float, default=0.1, help='The hyper parameter for fedprox')
    parser.add_argument('--domain_keyed_proto', action='store_true', help='key global_proto by (class,domain) instead of class-only (default: False, original FedPall behavior)')
    parser.add_argument('--domain_keyed_proto_gpcl', action='store_true', help='within each (class,domain) key, combine multiple clients via GPCL-style distance weighting instead of simple sample-count-weighted averaging (default: False; requires --domain_keyed_proto to also be set, otherwise ignored)')
    parser.add_argument('--no_discriminator_fix', action='store_true', help='use the client-indexed discriminator instead of the domain-indexed one (default: False, domain-indexed)')
    parser.add_argument('--use_flat_gpcl', action='store_true', help='apply GPCL distance weighting flat across all clients, no domain grouping (mutually exclusive with --domain_keyed_proto)')
    parser.add_argument('--layer1_confidence_weighted', action='store_true', help='within each (class,domain) key, weight each client contribution by n/(n+c) (saturating confidence weight, see confidence_weight() in util.py) instead of simple sample-count-weighted averaging (default: False; requires --domain_keyed_proto; ignored if --domain_keyed_proto_gpcl is also set, which takes priority)')
    parser.add_argument('--mixup_lambda_min', type=float, default=0.7, help='for missing-class synthetic MixUp (see ours()/lambda_mixup): min weight on the received domain prototype when blending with a real partner sample from a different class (default 0.7, prototype-dominant since it is the only real signal about the missing class -- opposite emphasis from uniform_left/uniform_right, which is real-sample-dominant for classes the client already has)')
    parser.add_argument('--mixup_lambda_max', type=float, default=1.0, help='max weight on the received domain prototype for missing-class synthetic MixUp (see --mixup_lambda_min)')
    parser.add_argument('--adaptive_local_batch', action='store_true', help='fragmentation-aware local batch size: use B_i = min(--batch, ceil(n_i/2)) per client so every client keeps at least 2 minibatches per local epoch. Off by default (byte-identical to the fixed global batch). Self-targeting: on Office-10 it changes only the dslr clients (31-32 samples vs batch 32, currently 1 deterministic full-batch step per epoch) and leaves every larger client untouched')
    parser.add_argument('--mixup_support_threshold', type=int, default=0, help='a class is treated as needing synthetic MixUp support when this client holds <= this many local samples of it. 0 (default) = only literally-absent classes, byte-identical to the original missing-class behavior. k>0 broadens it to severely under-supported classes too -- self-targeting by design: at k=5 dslr (~3 samples per client-class at M=4) triggers nearly everywhere while amazon/caltech/webcam (~24-38 per client-class) essentially never do')
    parser.add_argument('--feat_loss_arg', type=float, default=0.1)
    parser.add_argument('--crt_feat_num', type=int, default=50)
    parser.add_argument('--ld', type = float, default= 1, help ='weight for fedproto mse loss')
    parser.add_argument('--mu', type=float, default=1e-2, help='The hyper parameter for fedprox')
    parser.add_argument('--alpha', default=1, type=float, help='the hypeparameter for BKD2 loss')
    parser.add_argument('--T', default=3.0, type=float, help='Input the temperature: default(3.0)')
    parser.add_argument('--beta', type=float, default=1e-2, help ='beta for perfedavg')
    parser.add_argument('--tau', type=float, default=1, help ='temperature coefficient')
    parser.add_argument('--times', type=float, default=1.0)
    parser.add_argument('--lamb', type=float, default=100, help="CE loss weight parameter")
    parser.add_argument('--std_coeff', type=float, default=2.5, help='the lambda parameter for FedUV')
    parser.add_argument('--unif_coeff', type=float, default=0.5, help='the mu parameter for FedUV')

    args = parser.parse_args()
    return args

